import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import HomeComponent from '@/src/components/home-components/HomeComponents';
import styled from 'styled-components';
import { useState } from 'react';

const StyledHTML = styled.div`
  font-size: 62.5% !important;
  scroll-behavior: smooth;
`;

const Body = styled.main`
  max-width: 100vw;
  overflow-x: hidden;
  font-family: 'Gilroy-Medium', sans-serif;
  line-height: 1.5;
  box-sizing: border-box;
  text-rendering: optimizeSpeed;
`;

export default function Home() {
  return (
    <StyledHTML>
      <Head>
        <title>Capichi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <Body>
        <HomeComponent></HomeComponent>
      </Body>
    </StyledHTML>
  );
};